In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv('../train_with_5_parquet.csv')
train.head()

,Unnamed: 0,ID,State.Name,Year,Age,Incidence,"('Arithmetic.Mean', '1,1,2,2-Tetrachloroethane')_x","('Arithmetic.Mean', '1,2-Dichloropropane')_x","('Arithmetic.Mean', '1,3-Butadiene')_x","('Arithmetic.Mean', 'Acetaldehyde')_x",...,"('Arithmetic.Mean', 'o-Ethyltoluene')","('Arithmetic.Mean', 'o-Xylene')","('Arithmetic.Mean', 'p-Diethylbenzene')","('Arithmetic.Mean', 'p-Ethyltoluene')","('Arithmetic.Mean', 'tert-Butyl ethyl ether')","('Arithmetic.Mean', 'tert-butyl alcohol')","('Arithmetic.Mean', 'trans-1,2-Dichloroethylene')","('Arithmetic.Mean', 'trans-1,3-Dichloropropene')","('Arithmetic.Mean', 'trans-2-Butene')","('Arithmetic.Mean', 'trans-2-Pentene')"
0,0,f8312a4,Alabama,1990,65-69,4685.284313,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3effa36,Alabama,1990,70-74,4827.052043,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1e8044b,Alabama,1990,75-79,4377.956914,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,d875d65,Alabama,1990,80-84,3822.732993,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,46e6695,Alabama,1990,85-89,3470.199503,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
train.drop(columns=['Unnamed: 0'], inplace=True)

In [4]:
test = pd.read_csv('../test_with_5_parquet.csv')
test.head()

,Unnamed: 0,ID,State.Name,Year,Age,"('Arithmetic.Mean', '1,1,2,2-Tetrachloroethane')_x","('Arithmetic.Mean', '1,2-Dichloropropane')_x","('Arithmetic.Mean', '1,3-Butadiene')_x","('Arithmetic.Mean', 'Acetaldehyde')_x","('Arithmetic.Mean', 'Acrolein - Unverified')_x",...,"('Arithmetic.Mean', 'o-Ethyltoluene')","('Arithmetic.Mean', 'o-Xylene')","('Arithmetic.Mean', 'p-Diethylbenzene')","('Arithmetic.Mean', 'p-Ethyltoluene')","('Arithmetic.Mean', 'tert-Butyl ethyl ether')","('Arithmetic.Mean', 'tert-butyl alcohol')","('Arithmetic.Mean', 'trans-1,2-Dichloroethylene')","('Arithmetic.Mean', 'trans-1,3-Dichloropropene')","('Arithmetic.Mean', 'trans-2-Butene')","('Arithmetic.Mean', 'trans-2-Pentene')"
0,0,6c06615,Delaware,1990,65-69,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,e0cf76e,Delaware,1990,70-74,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,e9f95f0,Delaware,1990,75-79,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,5dffe44,Delaware,1990,80-84,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,9f9ea9b,Delaware,1990,85-89,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
test.drop(columns=['Unnamed: 0'], inplace=True)

In [6]:
train.isnull().sum()

ID                                                      0
State.Name                                              0
Year                                                    0
Age                                                     0
Incidence                                               0
                                                     ...
('Arithmetic.Mean', 'tert-butyl alcohol')            4422
('Arithmetic.Mean', 'trans-1,2-Dichloroethylene')    2826
('Arithmetic.Mean', 'trans-1,3-Dichloropropene')     2262
('Arithmetic.Mean', 'trans-2-Butene')                2970
('Arithmetic.Mean', 'trans-2-Pentene')               2988
Length: 172, dtype: int64

### Frist dataset: fill NA with 0

In [19]:
train = train.fillna(0)
train.head()

,ID,State.Name,Year,Age,Incidence,"('Arithmetic.Mean', '1,1,2,2-Tetrachloroethane')_x","('Arithmetic.Mean', '1,2-Dichloropropane')_x","('Arithmetic.Mean', '1,3-Butadiene')_x","('Arithmetic.Mean', 'Acetaldehyde')_x","('Arithmetic.Mean', 'Acrolein - Unverified')_x",...,"('Arithmetic.Mean', 'o-Ethyltoluene')","('Arithmetic.Mean', 'o-Xylene')","('Arithmetic.Mean', 'p-Diethylbenzene')","('Arithmetic.Mean', 'p-Ethyltoluene')","('Arithmetic.Mean', 'tert-Butyl ethyl ether')","('Arithmetic.Mean', 'tert-butyl alcohol')","('Arithmetic.Mean', 'trans-1,2-Dichloroethylene')","('Arithmetic.Mean', 'trans-1,3-Dichloropropene')","('Arithmetic.Mean', 'trans-2-Butene')","('Arithmetic.Mean', 'trans-2-Pentene')"
0,f8312a4,Alabama,1990,65-69,4685.284313,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,3effa36,Alabama,1990,70-74,4827.052043,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1e8044b,Alabama,1990,75-79,4377.956914,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,d875d65,Alabama,1990,80-84,3822.732993,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,46e6695,Alabama,1990,85-89,3470.199503,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
test = test.fillna(0)
test.head()

,ID,State.Name,Year,Age,"('Arithmetic.Mean', '1,1,2,2-Tetrachloroethane')_x","('Arithmetic.Mean', '1,2-Dichloropropane')_x","('Arithmetic.Mean', '1,3-Butadiene')_x","('Arithmetic.Mean', 'Acetaldehyde')_x","('Arithmetic.Mean', 'Acrolein - Unverified')_x","('Arithmetic.Mean', 'Acrolein - Verified')_x",...,"('Arithmetic.Mean', 'o-Ethyltoluene')","('Arithmetic.Mean', 'o-Xylene')","('Arithmetic.Mean', 'p-Diethylbenzene')","('Arithmetic.Mean', 'p-Ethyltoluene')","('Arithmetic.Mean', 'tert-Butyl ethyl ether')","('Arithmetic.Mean', 'tert-butyl alcohol')","('Arithmetic.Mean', 'trans-1,2-Dichloroethylene')","('Arithmetic.Mean', 'trans-1,3-Dichloropropene')","('Arithmetic.Mean', 'trans-2-Butene')","('Arithmetic.Mean', 'trans-2-Pentene')"
0,6c06615,Delaware,1990,65-69,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,e0cf76e,Delaware,1990,70-74,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,e9f95f0,Delaware,1990,75-79,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,5dffe44,Delaware,1990,80-84,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,9f9ea9b,Delaware,1990,85-89,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
train_dummy = pd.get_dummies(train, columns=['Age'], drop_first=True)
train_dummy.head()

,ID,State.Name,Year,Incidence,"('Arithmetic.Mean', '1,1,2,2-Tetrachloroethane')_x","('Arithmetic.Mean', '1,2-Dichloropropane')_x","('Arithmetic.Mean', '1,3-Butadiene')_x","('Arithmetic.Mean', 'Acetaldehyde')_x","('Arithmetic.Mean', 'Acrolein - Unverified')_x","('Arithmetic.Mean', 'Acrolein - Verified')_x",...,"('Arithmetic.Mean', 'tert-butyl alcohol')","('Arithmetic.Mean', 'trans-1,2-Dichloroethylene')","('Arithmetic.Mean', 'trans-1,3-Dichloropropene')","('Arithmetic.Mean', 'trans-2-Butene')","('Arithmetic.Mean', 'trans-2-Pentene')",Age_70-74,Age_75-79,Age_80-84,Age_85-89,Age_90-94
0,f8312a4,Alabama,1990,4685.284313,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
1,3effa36,Alabama,1990,4827.052043,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0
2,1e8044b,Alabama,1990,4377.956914,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0
3,d875d65,Alabama,1990,3822.732993,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,1,0,0
4,46e6695,Alabama,1990,3470.199503,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,1,0

In [22]:
test_dummy = pd.get_dummies(test, columns=['Age'], drop_first=True)
test_dummy.head()

,ID,State.Name,Year,"('Arithmetic.Mean', '1,1,2,2-Tetrachloroethane')_x","('Arithmetic.Mean', '1,2-Dichloropropane')_x","('Arithmetic.Mean', '1,3-Butadiene')_x","('Arithmetic.Mean', 'Acetaldehyde')_x","('Arithmetic.Mean', 'Acrolein - Unverified')_x","('Arithmetic.Mean', 'Acrolein - Verified')_x","('Arithmetic.Mean', 'Arsenic (TSP) STP')",...,"('Arithmetic.Mean', 'tert-butyl alcohol')","('Arithmetic.Mean', 'trans-1,2-Dichloroethylene')","('Arithmetic.Mean', 'trans-1,3-Dichloropropene')","('Arithmetic.Mean', 'trans-2-Butene')","('Arithmetic.Mean', 'trans-2-Pentene')",Age_70-74,Age_75-79,Age_80-84,Age_85-89,Age_90-94
0,6c06615,Delaware,1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,0,0
1,e0cf76e,Delaware,1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,0,0,0,0
2,e9f95f0,Delaware,1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,1,0,0,0
3,5dffe44,Delaware,1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,1,0,0
4,9f9ea9b,Delaware,1990,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0,0,0,1,0

In [23]:
train_dummy.to_csv('../train_model.csv')

In [24]:
test_dummy.to_csv('../test_model.csv')

In [10]:
train.shape

(4500, 172)

In [11]:
train.isnull().mean()

ID                                                   0.000000
State.Name                                           0.000000
Year                                                 0.000000
Age                                                  0.000000
Incidence                                            0.000000
                                                       ...
('Arithmetic.Mean', 'tert-butyl alcohol')            0.982667
('Arithmetic.Mean', 'trans-1,2-Dichloroethylene')    0.628000
('Arithmetic.Mean', 'trans-1,3-Dichloropropene')     0.502667
('Arithmetic.Mean', 'trans-2-Butene')                0.660000
('Arithmetic.Mean', 'trans-2-Pentene')               0.664000
Length: 172, dtype: float64

In [13]:
na_counts = train.isnull().sum()

In [ ]:
lead_trans.dropna(thresh = lead_trans.shape[0]*.20 , axis = 1, inplace = True)